have_fun: false

memory_config:
  disabled: false

code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: 30

  pull_request_opened:
    help: false
    summary: true
    code_review: true
    include_drafts: true

ignore_patterns:
  - ".github/**"
  - "legacy/**"
  - "courses/Blazor/**"
  - "courses/old-web/**"
  - "courses/python/**"
  - "courses/xamarin/**"
  - "processes/archive/**"
